language: python

python:
   - "2.7"
   - "3.6"

matrix:
 allow_failures:
   - python: "3.6"

env:
  - REPOSITORY="uc-cdis/cirrus" PR_NUMBER="$TRAVIS_PULL_REQUEST"

install:
   - python setup.py install
   - pip install -r dev-requirements.txt
   - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -e git+https://git@github.com/uc-cdis/wool.git#egg=wool; fi

script:
  - py.test -vv --cov=cirrus --cov-report xml ./test

after_script:
  - python-codacy-coverage -r coverage.xml
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 && $PR_NUMBER != false ]]; then wool; fi
