import os

GOOGLE_API_KEY = os.environ["GOOGLE_API_KEY"]
GOOGLE_PROJECT_ID = os.environ["GOOGLE_PROJECT_ID"]
GOOGLE_APPLICATION_CREDENTIALS = os.environ["GOOGLE_APPLICATION_CREDENTIALS"]
GOOGLE_ADMIN_EMAIL = os.environ["GOOGLE_ADMIN_EMAIL"]

GOOGLE_IDENTITY_DOMAIN = os.environ["GOOGLE_IDENTITY_DOMAIN"]
# admin email for admin domain-wide service account to act for
GOOGLE_CLOUD_IDENTITY_ADMIN_EMAIL = os.environ["GOOGLE_CLOUD_IDENTITY_ADMIN_EMAIL"]

SERVICE_KEY_EXPIRATION_IN_DAYS = 10
