name: PyPI Test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize]
jobs:
  PyPIPoetryPublish:
    name: PyPI Poetry Publish
    uses: uc-cdis/.github/.github/workflows/python_package_index_publish.yaml@feat/pypi
    with:
        PYTHON_VERSION: '3.9'
        IS_TEST_PUBLISH: true
        PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
        PYPI_PROD_API_TOKEN: ${{ secrets.PYPI_PROD_API_TOKEN }}